<?php
$templateHintsEnabled = (bool) Mage::getStoreConfig('dev/debug/template_hints');
$extendedTemplateHintsEnabled = (bool) Mage::getStoreConfig('dev/tb_develop/extended_template_hints');
$translateInlineEnabled = (bool) Mage::getStoreConfig('dev/translate_inline/active');
$logEnabled = (bool) Mage::getStoreConfig('dev/log/active');
$systemLog = Mage::helper('develop')->readSystemLog();
$exceptionLog = Mage::helper('develop')->readExceptionLog();
$backtrace = Mage::helper('develop')->getBacktrace();
$backtraceTotal = count($backtrace);
$timers = Mage::helper('develop')->getTimers();
$timersTotal = count($timers);
?>
<div id="tabs_dashboard_container">
    <ul class="tabs_dashboard_menu">
        <li class="toolbar_menu_current"><a id="toolbar_link_dashboard_1" href="javascript:void(0);" onClick="TB_Tab('dashboard', 1);">Home</a></li>
        <li><a id="toolbar_link_dashboard_2" href="javascript:void(0);" onClick="TB_Tab('dashboard', 2);">Modules</a></li>    
        <li><a id="toolbar_link_dashboard_3" href="javascript:void(0);" onClick="TB_Tab('dashboard', 3);">PHP Info</a></li> 
        <li><a id="toolbar_link_dashboard_4" href="javascript:void(0);" onClick="TB_Tab('dashboard', 4);">System Log</a></li> 
        <li><a id="toolbar_link_dashboard_5" href="javascript:void(0);" onClick="TB_Tab('dashboard', 5);">Exceptions Log</a></li> 
        <li><a id="toolbar_link_dashboard_6" href="javascript:void(0);" onClick="TB_Tab('dashboard', 6);">Backtrace</a></li>
        <li><a id="toolbar_link_dashboard_7" href="javascript:void(0);" onClick="TB_Tab('dashboard', 7);">Code Profiler</a></li> 
    </ul>
    <div class="tab_dashboard">
        <div id="tab_dashboard_1" class="tab_dashboard_content">
            <div class="toolbar_block_left toolbar_hints_block">
                <h4 class="toolbar_paragraph toolbar_center">Cache Management</h4>   
                <table class="toolbar_table toolbar_table_sortable">              
                    <thead>
                        <tr>
                            <th>Param</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Magento Cache</span></td>
                            <td>
                                <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/clearCache') ?>">
                                    Refresh
                                </a>
                            </td>
                        </tr>                            
                        <tr class="toolbar_table_even"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Catalog Images Cache</span></td>
                            <td>
                                <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/clearImagesCache') ?>">
                                    Refresh
                                </a>
                            </td>
                        </tr>
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Javasipt/CSS Cache</span></td>
                            <td>
                                <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/clearJsCssCache') ?>">
                                    Refresh
                                </a>
                            </td>
                        </tr> 
                    </tbody>
                </table>  
            </div>
            <div class="toolbar_block_left toolbar_hints_block">
                <h4 class="toolbar_paragraph toolbar_center">Template Path Hints</h4>                                   
                <table class="toolbar_table toolbar_table_sortable">              
                    <thead>
                        <tr>
                            <th>Param</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>     
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Magento Translate Inline</span></td>
                            <td>
                                <?php
                                if ($translateInlineEnabled) {
                                    echo '<span class="color_yes">Enabled</span>';
                                    $translateInlineAction = 'Disable';
                                } else {
                                    echo '<span class="color_no">Disabled</span>';
                                    $translateInlineAction = 'Enable';
                                }
                                ?>
                            </td>
                            <td><a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/toggleTranslateInline') ?>">
                                    <?php echo $translateInlineAction; ?>
                                </a></td>
                        </tr>   
                        <tr class="toolbar_table_even"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Magento Template Hints</span></td>
                            <td>
                                <?php
                                if ($templateHintsEnabled) {
                                    echo '<span class="color_yes">Enabled</span>';
                                    $templateHintsAction = 'Disable';
                                } else {
                                    echo '<span class="color_no">Disabled</span>';
                                    $templateHintsAction = 'Enable';
                                }
                                ?>
                            </td>
                            <td><a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/toggleTemplateHints') ?>">
                                    <?php echo $templateHintsAction; ?>
                                </a>
                            </td>
                        </tr>
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Extended Template Hints</span></td>
                            <td>
                                <?php
                                if ($extendedTemplateHintsEnabled) {
                                    echo '<span class="color_yes">Enabled</span>';
                                    $extendedTemplateHintsAction = 'Disable';
                                } else {
                                    echo '<span class="color_no">Disabled</span>';
                                    $extendedTemplateHintsAction = 'Enable';
                                }
                                ?>
                            </td>
                            <td><a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/toggleExtendedTemplate') ?>">
                                    <?php echo $extendedTemplateHintsAction; ?>
                                </a>
                            </td>
                        </tr>                    
                    </tbody>
                </table>
            </div>
            <div class="toolbar_block_left toolbar_hints_block">
                <h4 class="toolbar_paragraph toolbar_center">Other Actions</h4>   
                <table class="toolbar_table toolbar_table_sortable">              
                    <thead>
                        <tr>
                            <th>Param</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Magento Indexes</span></td>
                            <td>
                                <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/refreshIndexes') ?>">
                                    Refresh
                                </a>
                            </td>
                        </tr>
                        <tr class="toolbar_table_even"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Session Files</span></td>
                            <td>
                                <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/clearSessions') ?>">
                                    Clear
                                </a>
                            </td>
                        </tr> 
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left">
                                <span class="toolbar_table_syntax-attribute">
                                    <?php
                                    if ($logEnabled) {
                                        echo 'Logging';
                                        $logAction = 'Disable';
                                    } else {
                                        echo 'Logging';
                                        $logAction = 'Enable';
                                    }
                                    ?>
                                </span>
                            </td>
                            <td>
                                <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/toggleLog') ?>">
                                    <?php echo $logAction; ?>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>  
            </div>
            <div class="toolbar_block_left toolbar_hints_block">
                <h4 class="toolbar_paragraph toolbar_center">Information</h4>   
                <table class="toolbar_table toolbar_table_sortable">              
                    <thead>
                        <tr>
                            <th>Param</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Magento Version</span></td>
                            <td><span class="toolbar_table_syntax-string"><?php echo Mage::getEdition() . ' v.' . Mage::getVersion(); ?></span></td>
                        </tr>    
                        <tr class="toolbar_table_even"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Memory Usage</span></td>
                            <td><span class="toolbar_table_syntax-string"><?php echo Mage::helper('develop')->getMemoryPeakUsage(); ?></span></td>
                        </tr>    
                        <tr class="toolbar_table_odd"> 
                            <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute">Duration</span></td>
                            <td><span class="toolbar_table_syntax-string"><?php echo Mage::helper('develop')->getScriptDuration(); ?> sec</span></td>
                        </tr>                      
                    </tbody>
                </table>  
            </div>
            <div class="toolbar_clear"></div>
        </div>
        <div id="tab_dashboard_2" class="tab_dashboard_content" style="display: none;">
            <h4 class="toolbar_paragraph">Installed Extensions</h4>   
            <table class="toolbar_table toolbar_table_sortable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Code Pool</th>
                        <th>Version</th>
                        <th>Enabled</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $row = 1;
                    foreach ($this->getModules() as $name => $item) {
                        $color = ($item['enabled'] == 'Yes' ? 'color_yes' : 'color_no');
                        ?>
                        <tr class="<?php echo $row % 2 ? 'toolbar_table_odd' : 'toolbar_table_even' ?>">
                            <td><?php echo $row ?></td>
                            <td class="toolbar_table_left"><?php echo $name ?></td>
                            <td><span class="<?php echo ($item['pool'] == 'community' ? 'toolbar_table_syntax-attribute' : 'toolbar_table_syntax-string'); ?>"><?php echo $item['pool'] ?></span></td>
                            <td><?php echo $item['version'] ?></td>
                            <td><?php echo '<span class="' . $color . '">' . $item['enabled'] . '</span>' ?></td>
                            <td>
                                <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/toggleModule', array('_query' => array('data' => Mage::helper('develop')->getEncryptedData($name)))) ?>">
                                    <?php echo ($item['enabled'] == 'Yes' ? 'Disable' : 'Enable') ?>
                                </a>
                            </td>
                        </tr>
                        <?php
                        $row++;
                    }
                    ?>
                </tbody>
            </table>
        </div>  
        <div id="tab_dashboard_3" class="tab_dashboard_content" style="display: none;">
            <h4 class="toolbar_paragraph">PHP Information</h4>   
            <table class="toolbar_table toolbar_table_wrap toolbar_table_sortable">
                <col width="20%" />
                <col width="80%" />
                <thead>
                    <tr>
                        <th>Param</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $info = Mage::helper('develop')->phpinfo2array();
                    foreach ($info as $section => $item) {
                        if (is_array($item)) {
                            $row = 0;
                            ?>
                            <tr class="<?php echo $row % 2 ? 'toolbar_table_odd' : 'toolbar_table_even' ?>">                         
                                <td colspan="2"><h4 class="toolbar_paragraph"><?php echo $section; ?></h4></td>
                            </tr>
                            <?php
                            $row++;
                            foreach ($item as $param => $value) {
                                ?>
                                <tr class="<?php echo $row % 2 ? 'toolbar_table_odd' : 'toolbar_table_even' ?>"> 
                                    <td class="toolbar_table_left"><span class="toolbar_table_syntax-attribute"><?php echo $param ?></span></td>
                                    <td class="toolbar_table_left"><span class="toolbar_table_syntax-string">
                                            <?php
                                            if (is_array($value)) {
                                                foreach ($value as $k => $v) {
                                                    echo htmlentities($k) . ' => ' . htmlentities($v) . '<br/>';
                                                }
                                            } else {
                                                echo htmlentities($value);
                                            }
                                            ?>
                                        </span></td>
                                </tr>     
                                <?php
                                $row++;
                            }
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>  
        <div id="tab_dashboard_4" class="tab_dashboard_content" style="display: none;">
            <h4 class="toolbar_paragraph">System Log (last 100 lines)</h4> 
            <?php
            if ($logEnabled) {
                ?>
                <table class="toolbar_table toolbar_table_wrap toolbar_table_sortable">
                    <col width="3%" />
                    <col width="97%" />
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Line</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $num = 1;
                        foreach ($systemLog as $row => $line) {   
                            if($line == ''){
                                continue;
                            }
                            ?>
                            <tr class="<?php echo $row % 2 ? 'toolbar_table_odd' : 'toolbar_table_even' ?>"> 
                                <td><span class="toolbar_table_syntax-attribute"><?php echo $num; ?></span></td>
                                <td class="toolbar_table_left"><span class="toolbar_table_syntax-string">
                                        <?php
                                        echo htmlentities($line);
                                        ?>
                                    </span></td>
                            </tr>     
                            <?php
                            $num++;
                        }
                        ?>
                    </tbody>
                </table>

                <?php
            } else {
                ?>
                Log features disabled. <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/toggleLog') ?>">Enable Logging</a>.
                <?php
            }
            ?>
        </div> 
        <div id="tab_dashboard_5" class="tab_dashboard_content" style="display: none;">
            <h4 class="toolbar_paragraph">Exceptions Log (last 100 lines)</h4> 
            <?php
            if ($logEnabled) {
                ?>
                <table class="toolbar_table toolbar_table_wrap toolbar_table_sortable">
                    <col width="3%" />
                    <col width="97%" />
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Line</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $num = 1;
                        foreach ($exceptionLog as $row => $line) {   
                            if($line == ''){
                                continue;
                            }
                            ?>
                            <tr class="<?php echo $row % 2 ? 'toolbar_table_odd' : 'toolbar_table_even' ?>"> 
                                <td><span class="toolbar_table_syntax-attribute"><?php echo $num; ?></span></td>
                                <td class="toolbar_table_left"><span class="toolbar_table_syntax-string">
                                        <?php
                                        echo htmlentities($line);
                                        ?>
                                    </span></td>
                            </tr>     
                            <?php
                            $num++;
                        }
                        ?>
                    </tbody>
                </table>

                <?php
            } else {
                ?>
                Log features disabled. <a class="toolbar_link" href="<?php echo Mage::getUrl('develop/index/toggleLog') ?>">Enable Logging</a>.
                <?php
            }
            ?>
        </div>  
        <div id="tab_dashboard_6" class="tab_dashboard_content" style="display: none;">
            <h4 class="toolbar_paragraph">Backtrace (<?php echo $backtraceTotal; ?> calls)</h4> 
                <table class="toolbar_table toolbar_table_wrap toolbar_table_sortable">
                    <col width="3%" />
                    <col width="25%" />
                    <col width="25%" />
                    <col width="3%" />
                    <col width="19%" />
                    <col width="20%" />
                    <col width="5%" />
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Method Call</th>
                            <th>File</th>
                            <th>Line</th>
                            <th>Details</th>                            
                            <th>Arguments</th>
                            <th>Call Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $num = 1;
                        foreach ($backtrace as $row => $line) {   
                            ?>
                            <tr class="<?php echo $row % 2 ? 'toolbar_table_odd' : 'toolbar_table_even' ?>"> 
                                <td><?php echo $num; ?></td>
                                <td class="toolbar_table_left">
                                <?php echo $line['method_name']; ?>
                                </td>
                                <td class="toolbar_table_left">
                                <?php echo htmlentities($line['file']); ?>
                                </td>
                                <td>
                                <?php echo $line['line']; ?>
                                </td>
                                <td class="toolbar_table_left">
                                <?php  
                                     if($line['object'] != ''){
                                         echo '<span class="toolbar_table_syntax-attribute">Object:</span> <span class="toolbar_table_syntax-string">' . $line['object'] . '</span><br/>';
                                     }
                                     if($line['class'] != ''){
                                         echo '<span class="toolbar_table_syntax-attribute">Class:</span> <span class="toolbar_table_syntax-string">' . $line['class'] . '</span><br/>';
                                     }
                                     if($line['function'] != ''){
                                         echo '<span class="toolbar_table_syntax-attribute">Function:</span> <span class="toolbar_table_syntax-string">' . $line['function'] . '</span><br/>';
                                     }
                                ?>
                                </td>
                                <td class="toolbar_table_left">
                                <?php 
                                   foreach($line['args'] as $k => $v){                                       
                                       echo '<span class="toolbar_table_syntax-attribute">' . $k . '</span> => <span class="toolbar_table_syntax-string">' . $v . '</span><br/>';
                                   } 
                                ?>
                                </td>
                                <td>
                                <?php echo htmlentities($line['call_type']); ?>
                                </td>
                            </tr>     
                            <?php
                            $num++;
                        }
                        ?>
                    </tbody>
                </table>
        </div> 
        <div id="tab_dashboard_7" class="tab_dashboard_content" style="display: none;">
            <h4 class="toolbar_paragraph">Code Profiler (<?php echo $timersTotal; ?> profiled items)</h4> 
                <table class="toolbar_table toolbar_table_wrap toolbar_table_sortable">
                    <col width="3%" />
                    <col width="55%" />
                    <col width="7%" />
                    <col width="5%" />
                    <col width="15%" />
                    <col width="15%" />
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Code Profiler</th>
                            <th>Time, sec</th>
                            <th>Count</th>
                            <th>Emalloc</th>                            
                            <th>RealMem</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $num = 1;
                        foreach ($timers as $row => $line) {   
                            ?>
                            <tr class="<?php echo $row % 2 ? 'toolbar_table_odd' : 'toolbar_table_even' ?>"> 
                                <td><?php echo $num; ?></td>
                                <td class="toolbar_table_left">
                                <?php echo $line['timer'] ?>
                                </td>
                                <td>
                                <?php echo $line['sum']; ?>
                                </td>
                                <td>
                                <?php echo $line['count']; ?>
                                </td>
                                <td>
                                    <span class="toolbar_table_syntax-attribute">
                                    <?php echo $line['realmem']; ?>
                                    </span>
                                </td>
                                <td>
                                    <span class="toolbar_table_syntax-string">
                                    <?php echo $line['emalloc']; ?>
                                    </span>
                                </td>

                            </tr>     
                            <?php
                            $num++;
                        }
                        ?>
                    </tbody>
                </table>
        </div> 
    </div>
</div>
<div class="toolbar_clear"></div>